// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxifyjdptzkghbtqyjjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4aWZ5amRwdHprZ2hidHF5ampyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MTQwMDYsImV4cCI6MjA1MzQ5MDAwNn0.CFC_J11TB2PtTCvh2Rrq5JddK6CGhLiI8fmCxTM35oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);